const National = require('../model/national');
module.exports = {
    u_get_index: function () {

        let a = [{"name": " CHND Trung Hoa", "code": 1},
            {"name": " Ấn Độ", "code": 2},
            {"name": " Hoa Kỳ", "code": 3},
            {"name": " Indonesia", "code": 4},
            {"name": " Brazil", "code": 5},
            {"name": " Pakistan", "code": 6},
            {"name": " Nigeria", "code": 7},
            {"name": " Bangladesh", "code": 8},
            {"name": " Liên Bang Nga", "code": 9},
            {"name": " Nhật Bản", "code": 10},
            {"name": " Mexico", "code": 11},
            {"name": " Philippines", "code": 12},
            {"name": " Ethiopia", "code": 13},
            {"name": " Việt Nam", "code": 14},
            {"name": " Ai Cập", "code": 15},
            {"name": " Đức", "code": 16},
            {"name": " Thổ Nhĩ Kỳ", "code": 17},
            {"name": " Iran", "code": 18},
            {"name": " CHDC Congo", "code": 19},
            {"name": " Thái Lan", "code": 20},
            {"name": " Pháp", "code": 21},
            {"name": " Anh Quốc", "code": 22},
            {"name": " Ý", "code": 23},
            {"name": " Myanmar", "code": 24},
            {"name": " Hàn Quốc", "code": 25},
            {"name": " Nam Phi", "code": 26},
            {"name": " Tanzania", "code": 27},
            {"name": " Tây Ban Nha", "code": 28},
            {"name": " Colombia", "code": 29},
            {"name": " Ukraina", "code": 30},
            {"name": " Kenya", "code": 31},
            {"name": " Argentina", "code": 32},
            {"name": " Ba Lan", "code": 33},
            {"name": " Algeria", "code": 34},
            {"name": " Sudan", "code": 35},
            {"name": " Uganda", "code": 36},
            {"name": " Canada", "code": 37},
            {"name": " Maroc", "code": 38},
            {"name": " Iraq", "code": 39},
            {"name": " Afghanistan", "code": 40},
            {"name": " Nepal", "code": 41},
            {"name": " Peru", "code": 42},
            {"name": " Malaysia", "code": 43},
            {"name": " Uzbekistan", "code": 44},
            {"name": " Venezuela", "code": 45},
            {"name": " Ả Rập Saudi", "code": 46},
            {"name": " Yemen", "code": 47},
            {"name": " Ghana", "code": 48},
            {"name": " CHDCND Triều Tiên", "code": 49},
            {"name": " Mozambique", "code": 50},
            {"name": " Trung Hoa Dân Quốc (Đài Loan)", "code": 51},
            {"name": " Madagascar", "code": 52},
            {"name": " Syria", "code": 53},
            {"name": " Bờ Biển Ngà", "code": 54},
            {"name": " Úc", "code": 55},
            {"name": " Romania", "code": 56},
            {"name": " Sri Lanka", "code": 57},
            {"name": " Cameroon", "code": 58},
            {"name": " Angola", "code": 59},
            {"name": " Burkina Faso", "code": 60},
            {"name": " Kazakhstan", "code": 61},
            {"name": " Chile", "code": 62},
            {"name": " Niger", "code": 63},
            {"name": " Hà Lan", "code": 64},
            {"name": " Malawi", "code": 65},
            {"name": " Mali", "code": 66},
            {"name": " Ecuador", "code": 67},
            {"name": " Campuchia", "code": 68},
            {"name": " Guatemala", "code": 69},
            {"name": " Zambia", "code": 70},
            {"name": " Senegal", "code": 71},
            {"name": " Zimbabwe", "code": 72},
            {"name": " Tchad", "code": 73},
            {"name": " Hy Lạp", "code": 74},
            {"name": " Cuba", "code": 75},
            {"name": " Bỉ", "code": 76},
            {"name": " Bồ Đào Nha", "code": 77},
            {"name": " Tunisia", "code": 78},
            {"name": " Cộng hòa Séc", "code": 79},
            {"name": " Bolivia", "code": 80},
            {"name": " Rwanda", "code": 81},
            {"name": " Guinea", "code": 82},
            {"name": " Haiti", "code": 83},
            {"name": " Hungary", "code": 84},
            {"name": " Belarus", "code": 85},
            {"name": " Thụy Điển", "code": 86},
            {"name": " Cộng hòa Dominica", "code": 87},
            {"name": " Somalia", "code": 88},
            {"name": " Azerbaijan", "code": 89},
            {"name": " Benin", "code": 90},
            {"name": " Burundi", "code": 91},
            {"name": " Áo", "code": 92},
            {"name": " Các tiểu vương quốc Ả rập thống nhất (UEA)", "code": 93},
            {"name": " Nam Sudan", "code": 94},
            {"name": " Honduras", "code": 95},
            {"name": " Thụy Sĩ", "code": 96},
            {"name": " Israel", "code": 97},
            {"name": " Bulgaria", "code": 98},
            {"name": " Serbia", "code": 99},
            {"name": " Tajikistan", "code": 100},
            {"name": " Hồng Kông", "code": 101},
            {"name": " Papua New Guinea", "code": 102},
            {"name": " Togo", "code": 103},
            {"name": " Libya", "code": 104},
            {"name": " Jordan", "code": 105},
            {"name": " Paraguay", "code": 106},
            {"name": " Lào", "code": 107},
            {"name": " El Salvador", "code": 108},
            {"name": " Sierra Leone", "code": 109},
            {"name": " Nicaragua", "code": 110},
            {"name": " Đan Mạch", "code": 111},
            {"name": " Slovakia", "code": 112},
            {"name": " Kyrgyzstan", "code": 113},
            {"name": " Phần Lan", "code": 114},
            {"name": " Eritrea", "code": 115},
            {"name": " Turkmenistan", "code": 116},
            {"name": " Singapore", "code": 117},
            {"name": " Na Uy", "code": 118},
            {"name": " Costa Rica", "code": 119},
            {"name": " Cộng hòa Trung Phi", "code": 120},
            {"name": " Ireland", "code": 121},
            {"name": " Gruzia", "code": 122},
            {"name": " Croatia", "code": 123},
            {"name": " New Zealand", "code": 124},
            {"name": " Liban", "code": 125},
            {"name": " Liberia", "code": 126},
            {"name": " Vùng lãnh thổ Palestine", "code": 127},
            {"name": " Bosna và Hercegovina", "code": 128},
            {"name": " Cộng hòa Congo", "code": 129},
            {"name": " Puerto Rico", "code": 130},
            {"name": " Moldova", "code": 131},
            {"name": " Panama", "code": 132},
            {"name": " Mauritania", "code": 133},
            {"name": " Uruguay", "code": 134},
            {"name": " Armenia", "code": 135},
            {"name": " Litva", "code": 136},
            {"name": " Albania", "code": 137},
            {"name": " Kuwait", "code": 138},
            {"name": " Mông Cổ", "code": 139},
            {"name": " Jamaica", "code": 140},
            {"name": " Oman", "code": 141},
            {"name": " Latvia", "code": 142},
            {"name": " Namibia", "code": 143},
            {"name": " Lesotho", "code": 144},
            {"name": " Cộng hòa Macedonia", "code": 145},
            {"name": " Slovenia", "code": 146},
            {"name": " Botswana", "code": 147},
            {"name": " Gambia", "code": 148},
            {"name": " Qatar", "code": 149},
            {"name": " Guinea-Bissau", "code": 150},
            {"name": " Gabon", "code": 151},
            {"name": " Estonia", "code": 152},
            {"name": " Trinidad và Tobago", "code": 153},
            {"name": " Mauritius", "code": 154},
            {"name": " Bahrain", "code": 155},
            {"name": " Swaziland", "code": 156},
            {"name": " Đông Timor", "code": 157},
            {"name": " Djibouti", "code": 158},
            {"name": " Fiji", "code": 159},
            {"name": " Síp", "code": 160},
            {"name": " Guyana", "code": 161},
            {"name": " Comoros", "code": 162},
            {"name": " Guinea Xích Đạo ", "code": 163},
            {"name": " Bhutan", "code": 164},
            {"name": " Montenegro", "code": 165},
            {"name": " Macau", "code": 166},
            {"name": " Tây Sahara", "code": 167},
            {"name": " Quần đảo Solomon", "code": 168},
            {"name": " Suriname", "code": 169},
            {"name": " Luxembourg", "code": 170},
            {"name": " Cape Verde", "code": 171},
            {"name": " Malta", "code": 172},
            {"name": " Brunei", "code": 173},
            {"name": " Bahamas", "code": 174},
            {"name": " Belize", "code": 175},
            {"name": " Iceland", "code": 176},
            {"name": " Maldives", "code": 177},
            {"name": " Barbados", "code": 178},
            {"name": " Vanuatu", "code": 179},
            {"name": " Samoa", "code": 180},
            {"name": " Guam", "code": 181},
            {"name": " Saint Lucia", "code": 182},
            {"name": " São Tomé và Príncipe", "code": 183},
            {"name": " Curaçao", "code": 184},
            {"name": " Saint Vincent và Grenadines", "code": 185},
            {"name": " Quần đảo Virgin thuộc Mỹ", "code": 186},
            {"name": " Aruba", "code": 187},
            {"name": " Grenada", "code": 188},
            {"name": " Tonga", "code": 189},
            {"name": " Liên bang Micronesia", "code": 190},
            {"name": " Kiribati", "code": 191},
            {"name": " Jersey", "code": 192},
            {"name": " Antigua và Barbuda", "code": 193},
            {"name": " Seychelles", "code": 194},
            {"name": " Andorra", "code": 195},
            {"name": " Đảo Man", "code": 196},
            {"name": " Samoa thuộc Mỹ", "code": 197},
            {"name": " Dominica", "code": 198},
            {"name": " Bermuda", "code": 199},
            {"name": " Guernsey", "code": 200},
            {"name": " Quần đảo Bắc Mariana", "code": 201},
            {"name": " Greenland", "code": 202},
            {"name": " Quần đảo Cayman", "code": 203},
            {"name": " Quần đảo Marshall", "code": 204},
            {"name": " Saint Kitts và Nevis", "code": 205},
            {"name": " Quần đảo Faroe", "code": 206},
            {"name": " Quần đảo Turks và Caicos", "code": 207},
            {"name": " Sint Maarten", "code": 208},
            {"name": " Liechtenstein", "code": 209},
            {"name": " Monaco", "code": 210},
            {"name": " San Marino", "code": 211},
            {"name": " Gibraltar", "code": 212},
            {"name": " Quần đảo Virgin thuộc Anh", "code": 213},
            {"name": " Quần đảo Cook", "code": 214},
            {"name": " Palau", "code": 215},
            {"name": " Anguilla", "code": 216},
            {"name": " Nauru", "code": 217},
            {"name": " Tuvalu", "code": 218},
            {"name": " Montserrat", "code": 219},
            {"name": " Saint Helena, Ascension và Tristan da Cunha", "code": 220},
            {"name": " Quần đảo Falkland", "code": 221},
            {"name": " Niue", "code": 222},
            {"name": " Tokelau", "code": 223},
            {"name": " Vatican", "code": 224},
            {"name": " Quần đảo Pitcairn", "code": 225}]
        console.log("national request");
        // return National.remove({},function () {
        //
        // });
        // National.insertMany(a, function () {
        //
        // });
        return National.find().sort({name: 1});
    },

    u_delete_index: function (id) {
        console.log(id);
        return National.findByIdAndRemove(id);
    },
    u_put_index: function (data) {
        return National.findByIdAndUpdate(data._id, data);
    },
    u_post_index: function (data) {
        return National.find({}).sort({code: -1}).then(arr => {
            if (!Array.isArray(arr) || arr.length == 0) {
                data.code = 1;
            } else {
                data.code = arr[0].code + 1;
            }
            return National(data).save();
        })
    }
};
